apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    chart: mychart
    repoURL: https://github.com/reg117/sample-app.git
    targetRevision: 0.1.0
    path: dev
    helm:
      releaseName: mychart
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

