apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-argo-app
  namespace: argocd
spec: 
  project: default
  source: 
    path: dev
    repoURL: https://github.com/reg117/sample-app.git
    targetRevision: main
  destination: 
    namespace: myapp
    server: "https://kubernetes.default.svc"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
